import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import MainProvider from '@/providers'
import { SidebarProvider } from '@/providers/sidebarProvider'
import { Sidebar } from '@/components/sidebar'
import { SidebarContent } from '@/components/sidebar/sidebar-content'

const UniviaProUltra = localFont({
  src: './fonts/UniviaPro-Ultra.ttf',
  variable: '--font-univiapro-ultra',
  weight: '700',
  fallback: ['sans-serif', 'Arial'],
  preload: true,
  display: 'swap',
})
const UniviaProBold = localFont({
  src: './fonts/UniviaPro-Bold.ttf',
  variable: '--font-univiapro-bold',
  weight: '700',
  fallback: ['sans-serif', 'Arial'],
  preload: true,
  display: 'swap',
})
const UniviaProRegular = localFont({
  src: './fonts/UniviaPro-Regular.ttf',
  variable: '--font-univiapro-regular',
  weight: '400',
  fallback: ['sans-serif', 'Arial'],
  preload: true,
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Portfólio | Paulo Reis',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={`min-h-svh h-svh max-h-svh min-w-full w-full max-w-full overflow-hidden ${UniviaProUltra.variable} ${UniviaProRegular.variable} ${UniviaProBold.variable} antialiased`}
      >
        <MainProvider>
          <SidebarProvider>
            <Sidebar />
            <SidebarContent>{children}</SidebarContent>
          </SidebarProvider>
        </MainProvider>
      </body>
    </html>
  )
}
